#Menu jsou tlačítka pro navidgování skrz stránkách v pravidlech. Barevné kódy Minecraftu zde můžou být použity.
#Space = mezera mezi "Zpět" a "Další" a poté mezi "přijmout" a "odmítnout" tlačítkem.
Menu:
  BackButton: '&3<< &2Zpět'
  NextButton: '&2Další &3>>'
  AcceptButton: '&2>> Přijmout <<'
  DenyButton: '&4>> Odmítnout <<'
  Space: '               '
#"RulesPerPage" je počet pravidel na jednu stránku. Toto automaticky spočítá počet stránek.
#"RulesCooldown" je čas (v sekundách) kolik hráč musí být minimálně času na jedné stránce než může kliknout na "Další". Toto je proti přeskakování pravidel.
Page:
  RulesPerPage: 4
  RulesCooldown: 3
#"Parting" je patička a hlavička mezi jednotlivými sekcemi. Barevné Minecraft kódy zde mohou být užity.
Parting:
  Header: '&6__________________[ %page% / %maxpage% ]_____________________'
  Footer: '&6_____________________________________________'
  AcceptPageHeader: '&6_____________________________________________'
  AcceptPageFooter: '&6_____________________________________________'
  PlayerInfoHeader: '&6_____________________________________________'
  PlayerInfoFooter: '&6_____________________________________________'
  Default: '&6_____________________________________________'
#Zde jsou uvedeny příkazy které se použijí když hráč klikni na "přijmout" nebo "odmítnout"
#Příkazy jsou provedeny konzolí, hráč na ně nemusí mít permise. S "%player%" je použito hráčovo jméno.
#Barevné kódy můžou být použity v příkazech i ve zprávách.
#Pokud chceš, aby byl příkaz použit jako kdyby ho napsal manuálně hráč (který má permisi), přidej "%asPlayer%" na konci příkazu.
#Poznámka: Pokud hráč nebude mít permisi na použití příkazu, ukáže se mu "You do not have permission for this command" (Nemáš permise), přestože hráč neví, který příkaz použil.
Commands:
  AcceptedExecutes:
 - atrpublic &6%player% &fpřijmul pravidla serveru!
  DenyExecutes:
 - atrpublic &3%player% &fodmítl pravidla serveru!
#Příkazy které má hráč povolené použít přestože nepřijmul pravidla. V případě používání Authme se doporučuje připsat login/register. Platí pouze pokud -> "Prevent -> Commands = true"
  AllowedCommands:
  - rules
  - rule
  - atrnext
  - atrback
  - atraccept
  - atrdeny
  - atrprivate
  - atrpublic
#Pošle startovací zprávu (může být změněna v messages.yml souboru), a zpoždění zprávy po připojení.
StartMessage:
  Enable: true
  Delay: 0
#Zmrazí a zablokuje pohyb hráči, aby se soustředil na pravidla.
#Aby hráč nebyl spamován zprávama když se chce pohnout, je zde "MessageCooldown", který nastaví odezvu mezi zprávama (v sekundách)
Freeze:
  Enable: false
  MessageCooldown: 3
#Zabrání hráčovi používat různé níže uvedené akce. Pokud je hodnota nastavena na "true", hráč poté nemůže tyto níže uvedené akce dělat. (i.e. protekce je zapnuta).
#Doba opětovného použití příkazu je nastavena v sekundách
Prevent:
  Chat: false
  Commands: false
  Interact: false
  MessageCooldown: 3
#Pokud chceš, aby hráč pravidla přečetl a potvrdil jednou za X dní, nastav "Enable" na "true".
#Po X dnech bude muset hráč opětovně přečíst a potvrdit pravidla (automaticky)
#Dny jsou uvedeny jako reálné dny (24h). Nemají nic společného s minecraftím dnem.
Period:
  Enable: false
  Days: 90